// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
    
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // TODO (codelab user): Replace with your Firebase credentials
  // Generate this file with credentials with the FlutterFire CLI


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSajBC5FfUxTKRqxlx93wFvVDGHhBIKDo',
    appId: '1:970315434457:android:b2259c7dbbc9a353d471c8',
    messagingSenderId: '970315434457',
    projectId: 'fluttertest-24277',
    databaseURL: 'https://fluttertest-24277-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fluttertest-24277.appspot.com',
  );


}











